apiVersion: v1
kind: Service
metadata:
  name: nn-sq-svc
spec:
  type: LoadBalancer
  selector:
    app: nn-sq-train 
  ports:
  - name: redis-port
    protocol: TCP
    port: 6379
    targetPort: 6379
  - name: flask-port
    protocol: TCP
    port: 80
    targetPort: 5000
