apiVersion: apps/v1
kind: Deployment
metadata:
  name: nn-sq-train-deployment
  labels:
    app: nn-sq-train
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nn-sq-train
  template:
    metadata:
      labels:
        app: nn-sq-train
    spec:
      containers:
      - name: nn-train
        image: tseth/nn_train:1.0
        ports:
        - containerPort: 5000
      - name: redis-nn
        image: redis:latest
        ports:
        - containerPort: 6379
