apiVersion: v1
kind: Service
metadata:
  name: nn-sq-svc
  namespace: nn-sq
spec:
  selector:
    app: nn-sq-selector-app 
  ports:
  - name: redis-port
    protocol: TCP
    port: 6379
    targetPort: 6379
  - name: flask-port
    protocol: TCP
    port: 5000
    targetPort: 5000
