apiVersion: v1
kind: PersistentVolume
metadata:
  name: nn-disk
spec:
  #storageClassName: manual
  capacity:
    storage: 10Gi #Size of the volume
  accessModes:
    - ReadWriteMany #type of access
  #hostPath:
  #  path: "/mnt/data"
  nfs:
    path: /nn_fileshare
    server: 10.134.196.106
